# Generated by Django 4.1.13 on 2025-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
