# Generated by Django 4.1.13 on 2025-06-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_blogpost_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
